version: '3'
services:
  ros2_dev:
    build: .
    container_name: ros2_dev
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./lab2/:/ros2_ws/src/two_drones_pkg
    network_mode: host
    privileged: true
    command: bash
    stdin_open: true
    tty: true 